# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160614_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name=b'Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(null=True, verbose_name=b'Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_es',
            field=models.TextField(null=True, verbose_name=b'Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Nombre'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name=b'Nombre'),
        ),
    ]
